/**
 * 
 */
package kar.problem2;

/**
 * <strong>Even Fibonacci Numbers</strong>
 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:</p>
 * <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... </p>
 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 * @author Kelsey Robertson
 *
 */
public class Problem2Attempt1 {

	public static Integer output;
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		calculateFib(4000000);
		System.out.print(getEvenSum());

	}
	
	public static void calculateFib(Integer maxValue){
		int first = 1, second = 1, calc = 0, sum = 0;
		while(calc < maxValue){
			if(calc % 2 == 0){
				sum += calc;
			}
			calc = first + second;
			first = second;
			second = calc;
		}
		output = sum;
	}

	public static Integer getEvenSum(){
		return output;
	}
}
