package kar.problem2;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

/**
 * <strong>Even Fibonacci Numbers</strong>
 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:</p>
 * <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... </p>
 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 * @author Kelsey Robertson
 *
 */

public class Problem2Attempt1Test {

	@Before
	public void setUp() throws Exception {
	}

	@After
	public void tearDown() throws Exception {
	}

	/**
	 * The first 10 terms in the Fibonacci sequence are 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
	 * <p>The sum of the even number numbers are:
	 * </br>2 + 8 + 34 = 44.</p>
	 * <p>The test should be true if the problem is coded correctly. :)
	 */
	@Test
	public void testEvenValuedSum() {
		Integer test = 44;
		Problem2Attempt1.calculateFib(90);
		
		assertEquals(test, Problem2Attempt1.getEvenSum());
	}

}
